name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm curl unzip

    - name: Download and install ngrok
      run: |
        curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin

    - name: Authenticate ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}

    - name: Run Docker container with QEMU
      run: |
        docker run -d --name qemu-container -e "BOOT=https://bunny.deb.parrot.sh//parrot/iso/6.1/Parrot-security-6.1_amd64.iso" -p 8006:8006 --device=/dev/kvm --cap-add NET_ADMIN qemux/qemu-docker

    - name: Start ngrok
      run: ngrok http 8006 &

    - name: Get ngrok URL
      id: ngrok
      run: sleep 10 && curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url

    - name: Display ngrok URL
      run: echo "Ngrok URL: ${{ steps.ngrok.outputs.ngrok_url }}"
